In [1]:
from __future__ import print_function

In [2]:
import torch

##### Uninitialized Matrix

In [3]:
x = torch.Tensor(5,3)

In [4]:
print(x)


 0.0000e+00 -2.0000e+00  0.0000e+00
-2.0000e+00  2.2335e+08  2.2369e+08
 0.0000e+00  0.0000e+00  0.0000e+00
-2.0000e+00  0.0000e+00 -2.0000e+00
 8.4078e-45  0.0000e+00  0.0000e+00
[torch.FloatTensor of size 5x3]



##### Random Matrix

In [7]:
x = torch.rand(5,3)

In [8]:
print(x)


 0.4353  0.8811  0.2180
 0.7440  0.2087  0.7618
 0.9312  0.5613  0.2394
 0.4222  0.7533  0.1093
 0.8785  0.9013  0.3829
[torch.FloatTensor of size 5x3]



###### Get size

In [11]:
print(x.size())

torch.Size([5, 3])


###### Addition

#### Syntax 1 overloaded + operator

In [37]:
y= torch.rand(5,3)

print(x+y)


 0.5581  1.2125  1.1757
 1.2213  0.2857  0.9122
 0.9319  1.1520  0.5103
 1.0738  1.6250  0.6614
 1.7590  1.1682  0.5850
[torch.FloatTensor of size 5x3]



#### Syntax 2 .add() function

In [38]:
print(torch.add(x,y))


 0.5581  1.2125  1.1757
 1.2213  0.2857  0.9122
 0.9319  1.1520  0.5103
 1.0738  1.6250  0.6614
 1.7590  1.1682  0.5850
[torch.FloatTensor of size 5x3]



#### Giving an output tensor with .add(x,y,out=result)

In [39]:
result = torch.Tensor(5,3)

torch.add(x,y,out=result)

print(result)


 0.5581  1.2125  1.1757
 1.2213  0.2857  0.9122
 0.9319  1.1520  0.5103
 1.0738  1.6250  0.6614
 1.7590  1.1682  0.5850
[torch.FloatTensor of size 5x3]



#### Addition in-place with .add_()

In [40]:
y.add_(x)

print(y)


 0.5581  1.2125  1.1757
 1.2213  0.2857  0.9122
 0.9319  1.1520  0.5103
 1.0738  1.6250  0.6614
 1.7590  1.1682  0.5850
[torch.FloatTensor of size 5x3]



* Any in place operation uses _ at end of function like:
    * x.copy_(y)
    * x.t_()
both will change x

#### Yay Standard numpy-like Indexing!!! [:,1], etc

In [41]:
print(x)
print(x[:,1])


 0.4353  0.8811  0.2180
 0.7440  0.2087  0.7618
 0.9312  0.5613  0.2394
 0.4222  0.7533  0.1093
 0.8785  0.9013  0.3829
[torch.FloatTensor of size 5x3]


 0.8811
 0.2087
 0.5613
 0.7533
 0.9013
[torch.FloatTensor of size 5]



check out [these](http://pytorch.org/docs/torch) docs of pytorch operations later 

#### Converting to numpy with .numpy()

In [42]:
a = torch.ones(5)

print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [46]:
b = a.numpy()

print(b)

[ 1.  1.  1.  1.  1.]


#### The numpy array points to the torch array, so it will change if you change the torch one!

In [54]:
a.add_(1)

print(a)
print(b)


 7
 7
 7
 7
 7
[torch.FloatTensor of size 5]

[ 7.  7.  7.  7.  7.]


### Converting numpy array to torch Tensor

In [55]:
import numpy as np

In [58]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)
#cool!

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]

